services:
  - type: web
    name: webapps-lab4
    env: docker
    dockerfilePath: ./Dockerfile
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: TIDB_URL
        sync: false
      - key: TIDB_USERNAME
        sync: false
      - key: TIDB_PASSWORD
        sync: false
      - key: JAVA_OPTS
        value: "-Dspring.profiles.active=prod -Duser.timezone=UTC"
      - key: MAIL_HOST
        value: smtp.ethereal.email
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: wilmer.ankunding@ethereal.email
        sync: false
      - key: MAIL_PASSWORD
        value: GVDW5ZTPSSXuAnRh1y
        sync: false